/*  vortexdriver.c - The simplest kernel module.

* Copyright (C) 2013-2022 Xilinx, Inc
* Copyright (c) 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/

#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>
#include <linux/types.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>
#include <linux/platform_device.h>

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR("Rosilena");
MODULE_DESCRIPTION("vortexdriver - loadable module template generated by petalinux-create -t modules");
MODULE_VERSION("1.0");

#define DRIVER_NAME "vortexdriver"
#define DEVICE_NAME "vortex"
#define CLASS_NAME "vortex_class"
static int major_num;
static struct class* vortexClass = NULL;
static struct device* vortexDevice = NULL;

#define DCR 0
#define OFFSET_DCR_DATA 0
#define OFFSET_DCR_VALADDR 4
#define BRAM 1

struct vortexdriver_local {
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
};

struct vortexdriver_local devices[2];
static int index_devices = 0;

struct data_ioctl {
	u32 dcr_data;
	u32 dcr_valaddr;
};
	
#define IOCTL_READ	_IOR('k', 0, struct data_ioctl)
#define IOCTL_WRITE	_IOW('k', 1, struct data_ioctl)

/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
unsigned myint = 0xdeadbeef;
char *mystr = "default";

module_param(myint, int, S_IRUGO);
module_param(mystr, charp, S_IRUGO);

static ssize_t vortexdriver_read(struct file *file_ptr, char *buf, size_t count, loff_t *off) {
	char __iomem *bram_addr = (char __iomem *)devices[BRAM].base_addr;
	
	printk("Starting read....\n");
	if (copy_to_user(buf, bram_addr + *off, count)) {
		printk("Error!\n");
		return 0;
	}
	
	printk("Read %ld bytes\n", count);
	return count;
}

static ssize_t vortexdriver_write(struct file *file_ptr, const char *buf, size_t count, loff_t *off) {
	char __iomem *bram_addr = (char __iomem *)devices[BRAM].base_addr;
	
	printk("Starting write....\n");
	if (copy_from_user(bram_addr + *off, buf, count)) {
		printk("Error!\n");
		return 0;
	}
	
	printk("Wrote %ld bytes\n", count);
	return count;
}

static int vortexdriver_open(struct inode *inode, struct file *file_ptr){
	printk("Open!\n");
	for(int i=0; i<index_devices; i++){
		printk("Device %d at 0x%08x fino a 0x%08x mapped to 0x%08x\n", i, (unsigned int __force)devices[i].mem_start, (unsigned int __force)devices[i].mem_end, (unsigned int __force)devices[i].base_addr);
	}
	return 0;
}

static int vortexdriver_release(struct inode *inode, struct file *file_ptr){
	printk("Release!\n");
	return 0;
}

static inline void write_register_DCR(u32 reg_offset, u32 val)
{
	//u32 *addr = (u32*) (devices[DCR].base_addr + reg_offset);
	iowrite32(val, devices[DCR].base_addr + reg_offset);
	//*addr = val;
	printk("Writing\n");
	return;
};

static inline u32 read_register_DCR(u32 reg_offset)
{
	u32 val = 0;
	val = ioread32(devices[DCR].base_addr + reg_offset);
	return val;
};

static long vortexdriver_ioctl(struct file *file, unsigned int cmd, unsigned long arg){
	u32 val = 0;
	struct data_ioctl data_dcr;
	printk("Entered ioctl\n");
	
	switch(cmd) {
		case IOCTL_READ:
		{
			val = read_register_DCR(OFFSET_DCR_DATA);
			printk("The value of DCR_DATA %08x", val);
			val = read_register_DCR(OFFSET_DCR_VALADDR);
			printk("The value of DCR_VAL_ADDR %08x", val);
			break;
		}
		case IOCTL_WRITE:
		{
			if (copy_from_user(&data_dcr, (void __user *)arg, sizeof(data_dcr))){
				printk("Error!\n");
            			return -EFAULT;
            		}
			printk("DCR_DATA=0x%08x\n", (unsigned int __force) data_dcr.dcr_data);
			printk("DCR_VALADDR=0x%08x\n", (unsigned int __force) data_dcr.dcr_valaddr);
            		write_register_DCR(OFFSET_DCR_DATA, data_dcr.dcr_data);
            		write_register_DCR(OFFSET_DCR_VALADDR, data_dcr.dcr_valaddr);
            		printk("HO SCRITTO NEI REGISTRI DEL DCR\n");
			break;
		}
		default:
			return -EINVAL;
	}

	return 0;
}

struct file_operations Fops = {
	.owner 			= THIS_MODULE,
	.read		 	= vortexdriver_read,
	.write			= vortexdriver_write,
	.open 			= vortexdriver_open,
	.release		= vortexdriver_release,
	.unlocked_ioctl 	= vortexdriver_ioctl,
};


static irqreturn_t vortexdriver_irq(int irq, void *lp)
{
	printk("vortexdriver interrupt\n");
	return IRQ_HANDLED;
}


static int vortexdriver_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct vortexdriver_local *lp = NULL;

	int rc = 0;
	dev_info(dev, "Device Tree Probing\n");
	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	lp = (struct vortexdriver_local *) kmalloc(sizeof(struct vortexdriver_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate vortexdriver device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "vortexdriver: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	/* Get IRQ for the device */
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	if (!r_irq) {
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "vortexdriver at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->mem_start,
			(unsigned int __force)lp->base_addr);
			
		devices[index_devices].irq = r_irq;
		devices[index_devices].mem_start = lp->mem_start;
		devices[index_devices].mem_end = lp->mem_end;
		devices[index_devices].base_addr = lp->base_addr;
		index_devices++;
		return 0;
	}
	lp->irq = r_irq->start;
	rc = request_irq(lp->irq, &vortexdriver_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error3;
	}

	dev_info(dev,"vortexdriver at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
		
	devices[index_devices].irq = lp->irq;
	devices[index_devices].mem_start = lp->mem_start;
	devices[index_devices].mem_end = lp->mem_end;
	devices[index_devices].base_addr = lp->base_addr;
	index_devices++;
	return 0;
error3:
	free_irq(lp->irq, lp);
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static void vortexdriver_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct vortexdriver_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);
	iounmap(lp->base_addr);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
}


#ifdef CONFIG_OF
static struct of_device_id vortexdriver_of_match[] = {
	{ .compatible = "xlnx,DCR-Vortex-1.0"},
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, vortexdriver_of_match);
#else
# define vortexdriver_of_match
#endif


static struct platform_driver vortexdriver_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= vortexdriver_of_match,
	},
	.probe		= vortexdriver_probe,
	.remove		= vortexdriver_remove,
};

static int __init vortexdriver_init(void)
{
	printk("<1>Hello module world.\n");
	printk("<1>Module parameters were (0x%08x) and \"%s\"\n", myint,
	       mystr);
	       
	major_num = register_chrdev(0, DEVICE_NAME, &Fops);
	if (major_num < 0) {
		printk(KERN_ALERT "Failed to register a major number for the device.\n");
		return -1;
	}
	printk(KERN_INFO "Registration successful, the device's major number is %d.\n", major_num);

	vortexClass = class_create(CLASS_NAME);
	if (IS_ERR(vortexClass))
	{
		printk(KERN_ALERT "Failed to register class for the device.\n");
		goto error1;
	}
	printk(KERN_INFO "Class registration successful.\n");

	vortexDevice = device_create(vortexClass, NULL, MKDEV(major_num, 0), NULL, DEVICE_NAME);
	if (IS_ERR(vortexDevice))
	{
		printk(KERN_ALERT "Failed to create the device.\n");
		goto error2;
	}
	printk(KERN_INFO "Device created successfully.\n");

	return platform_driver_register(&vortexdriver_driver);
error2:
	class_destroy(vortexClass);
error1:
	unregister_chrdev(major_num,DEVICE_NAME);
	return -1;
}


static void __exit vortexdriver_exit(void)
{
	device_destroy(vortexClass, MKDEV(major_num, 0));
	class_unregister(vortexClass);
	class_destroy(vortexClass);
	unregister_chrdev(major_num, DEVICE_NAME);
	platform_driver_unregister(&vortexdriver_driver);
	printk(KERN_ALERT "Goodbye module world.\n");
}

module_init(vortexdriver_init);
module_exit(vortexdriver_exit);
